# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-15 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0003_auto_20170815_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=999, verbose_name='Order'),
        ),
    ]
