# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_topic_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['order', 'slug']},
        ),
        migrations.AddField(
            model_name='video',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', related_query_name='video', to='guide.Topic'),
            preserve_default=False,
        ),
    ]
