# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-16 16:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0005_auto_20170816_0908'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('file', models.FileField(upload_to=b'', verbose_name='Upload File')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', related_query_name='file', to='guide.Topic')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
