# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-10-16 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0006_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=512, verbose_name='Name')),
                ('url', models.URLField(verbose_name='URL')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', related_query_name='link', to='guide.Topic')),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
    ]
